apiVersion: v1
kind: Pod           
metadata:
  namespace: test
  labels:
    app: first-pod
  name: first-pod
spec:
  containers:
  - image: nginx
    name: first-pod 
    ports:
    - containerPort: 80
