apiVersion: v1
kind: Service
metadata:
  namespace: test
  labels:
    run: first-svc-np
  name: first-svc-np
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30200 # กำหนดหมายเลข NodePort (30000-32767)
  selector:
    run: first-pod
  type: NodePort # เพิ่มเติมในส่วนของประเภทให้เป็น NodePort