apiVersion: v1
kind: Service
metadata:
  namespace: test
  labels:
    run: first-svc-lb
  name: first-svc-lb
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: first-pod
  type: LoadBalancer # เพิ่ม Type เข้ามาให้เป็น LoadBalancer